---
- name: Install mssql-tools
  apt:
      name: mssql-tools
      state: present
      allow_unauthenticated: yes
  environment:
    ACCEPT_EULA: Y

- name: Install unixodbc-dev
  apt:
      name: unixodbc-dev
      state: present
      allow_unauthenticated: yes

- name: Add {{mssql_tools_path}} to path
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: 'PATH=(["]*)((?!.*?{{mssql_tools_path}}).*?)(["]*)$'
    line: 'PATH=\1\2:{{mssql_tools_path}}\3'

- name: Install sqlsrv
  pear:
    name: pecl/sqlsrv
    state: present

- name: Install pdo_sqlsrv
  pear:
    name: pecl/pdo_sqlsrv
    state: present

- name: Add pdo_sqlsrv to php.ini
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    line: 'extension=pdo_sqlsrv.so'
    state: present
  notify:
    - restart nginx
    - restart fpm

- name: Add sqlsrv to php.ini
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    line: 'extension=sqlsrv.so'
    state: present
  notify:
    - restart nginx
    - restart fpm

- name: Remove mssql container
  docker_container:
    name: mssql
    image: microsoft/mssql-server-linux:2017-latest
    state: absent
    
- name: Create mssql container
  docker_container:
    name: mssql
    image: microsoft/mssql-server-linux:2017-latest
    state: present
    command: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'sdt45gdsFa' -Q 'ALTER LOGIN SA WITH PASSWORD="sdt45gdsFaq"'
    env:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: sdt45gdsFa
        MSSQL_PID: Developer
    ports:
     - "1401:1433"

- name: Start mssql container
  docker_container:
    name: mssql
    image: microsoft/mssql-server-linux:2017-latest
    state: started
    env:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: sdt45gdsFaq
        MSSQL_PID: Developer
    ports:
     - "1401:1433"

- name: sleep for 15 seconds and continue with play
  wait_for: timeout=15
  delegate_to: localhost

- name: Copy db into container
  command: docker cp /var/www/ecbyo_sc.bak mssql:/var/opt/mssql/data

- name: Restore encbyo_db
  command: docker exec mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'sdt45gdsFaq' -Q "RESTORE DATABASE ecbyo_sc FROM DISK='/var/opt/mssql/data/ecbyo_sc.bak' WITH MOVE 'ecbyo_sc' TO '/var/opt/mssql/data/ecbyo_sc.mdf', MOVE 'ecbyo_sc_log' TO '/var/opt/mssql/data/ecbyo_sc_log.ldf'"