---
- hosts: ubuntu
  sudo: true
  vars:
  vars_files:
    - defaults/variables.yml

  roles:
    - initial
    - common
    - { role: geerlingguy.mysql }
    - { role: jdauphant.nginx }
    - { role: itcraftsmanpl.php7 }
    - { role: geerlingguy.docker }
    - mssql
    - adminer


#TODO: add hostname ubuntu to /etc/hostnames /etc/hosts
# curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-tools.list
# sudo apt-get update
# sudo ACCEPT_EULA=Y apt-get install mssql-tools
# sudo apt-get install unixodbc-dev
# echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
# echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
# source ~/.bashrc